{
	"category" : "KernelTests-Exception",
	"classinstvars" : [
		 ],
	"classvars" : [
		 ],
	"commentStamp" : "TorstenBergmann 2/5/2014 08:38",
	"instvars" : [
		 ],
	"name" : "MyResumableTestError",
	"pools" : [
		 ],
	"super" : "Error",
	"type" : "normal" }
